### ISSUE TITLE
Funktioniert nicht bei Upload per Drag & Drop in Gutenberg bzw. über REST API

### ISSUE THREAD

**Issue by goaround** [bueltge/de-DE#16]
Fügt man ein Bild per Drag & Drop in Gutenberg ein (nicht über das Media Model, sondern direkt in den Content), wird das Bild im Body per POST-Request an den REST API Endpoint /wp/v2/media gesendet.

Aktuell fügt deswegen dieses Plugin keinen Filter zu sanitize_file_name hinzu. Über die REST_REQUEST-Konstante, könnte man checken ob es sich um einen REST Request handelt. Allerdings wird die Konstate aktuell recht spät von WordPress initalisiert. Hier müsste man das Plugin erst bei rest_api_init ausführen, damit REST_REQUEST = true ist.

Außerdem gibt es ein weiteres Problem. Da der Upload im Body des Request erfolgt, wird der Filename aus dem Content-Disposition Header entnommen: https://github.com/WordPress/wordpress-develop/blob/4848b1e3aa956766d276d8f192ec398c01d6ace5/src/wp-includes/rest-api/endpoints/class-wp-rest-attachments-controller.php#L742

Deswegen wird der Title auch ohne Umlaute gespeichert.

Meine Idee wäre das Plugin zumindest bei init und rest_api_init zu laden weil aktuell wird aus allen Uploads die man per Drag & Drop in Gutenberg macht, keine Umlaute entfernt.

**Comment by goaround** [comment]
@bueltge hast du etwas Zeit dir das mal etwas anzuschauen?

**Comment by bueltge** [comment]
Hallo @goaround 
Das plugin wird aktuell ohne Hook inititiert, da es als Dropin daher kam und dies nicht nötig war. Damit rennt es zu früh los und die REST API bekommt die Korrektur der Dateien nicht mit. Heißt, die Konstanten Abfragen am ersten if-Statement sind nie true, wenn man `REST_REQUEST` einbaut. Wir müssen umbauen, das Plugin bei `plugins_loaded` oder `admin_init` laufen lassen und parallel die Dateinamen Anpassung ebenso bei `rest_api_init` inititieren und bei `wp_handle_upload_prefilter` laufen lassen.

**Comment by bueltge** [comment]
@goaround Ich habe die Lösung komplett neu geschrieben, da wir so triggern können und die REST API auch angesprochen werden kann. Kannst du das php File aus dem master-Branch testen, also Dropin/Plugin für alle Funktionen? In einem ersten Test Upload Files hat alles geklappt. Setzen des Feed-Sprach Key klappt auch.

**Comment by goaround** [comment]
@bueltge direkt getestet und der erste Test sah auf jeden Fall sehr gut aus. Zwar wird aus dem Titel auch die Umlaute entfernt. Ich denke, das ist aber zu verschmerzen.

Super, dass du dir die Mühe gemacht hast! Wirklich ein sehr nützliches Plugin. So muss ich nicht jedem Autor erklären, dass er ja alle Umlaute aus dem Dateinamen vor dem Upload entfernen soll. Klappt leider immer nur zu 80%...

**Comment by bueltge** [comment]
Sollen den im Titel die Umlaute bleiben, also im entstandenen Permalink? Der Title des Artikels oder andere CPT dürfen nicht verändert werden.

**Comment by goaround** [comment]
Wenn ich ein Bild `süße Katzen.jpg` hochlade, wäre es schon cool, wenn der Dateiname als Titel erhalten bleibt. 

Wenn ich das direkt im Media Model mache, bleibt der Titel ja genau so erhalten. Per Drag & Drop in Gutenberg wird daraus dann `suesse katzenbilder`. Die Groß- und Kleinschreibung geht leider auch verloren. 

![grafik](https://user-images.githubusercontent.com/5927337/78793602-ea48ca80-79b2-11ea-99fc-ee9848ae8061.png)

**Comment by bueltge** [comment]
Der Title wird aber nur so, wenn du das via Gutenberg, also REST API, tust - richtig? Sind sonst alle Funktionen sauber, wo man Bilder hochladen kann bzw. Permalink-Anpassung?

**Comment by goaround** [comment]
Genau, sonst funktioniert alles sauber.

**Comment by bueltge** [comment]
Ich habe diverse Sachen untersucht, aber das Ablegen des File passiert bei `_wp_handle_upload()` und darin habe ich nur File, ein Array mit dem Namen. Der 'post' wird via ' wp_insert_post' erzeugt. Wir könnten ggf. nur die ID des Attachments holen und dann den post für dieses Attachment neu schreiben, also einen ganzen Query mehr.

**Comment by goaround** [comment]
Wie oben bereits geschrieben: Ich denke, das kann man verschmerzen. Hauptsache es sind keine Umlaute im Dateinamen/Slug

**Comment by cfoellmann** [comment]
Da es eine „Performance“ Frage ist, könnte man den aktuellen Stand lassen und eine Konstante abfragen um den komplexeren Weg zu aktivieren. Oder deaktivieren.

Wenn man den. Zeit hat den noch einzuführen

**Comment by bueltge** [comment]
Aktuell ist der Permalink noch ohne Korrektur, wenn man via Gutenberg (REST API) Posts erstellt. Da will ich noch ran. Gibt es sonst noch Themen wo ggf. die alte Logik ohne REST API nicht mehr greift? Leider sind die Hooks zw. Classic und Gutenberg sehr unterschiedlich.

**Comment by bueltge** [comment]
@goaround Ich habe nun einen finalen Stand, würdest du nochmal rundherum testen.
An den Title via Rest komme ich aktuell nicht ran, ggf. findet da jemand was 
Ebenso bei dem Permalink im Gutenberg, der wird via AJAX gesetzt, generiert aus dem Title. Ich kann den zwar in der DB anpassen, dann aber mit Aufwand, da bereits 'sanitized' via WP, bspw. von `ä` nach `a` etc. Das wird schwer. Für den Eingriff in den AJAX Part fehlt mir das Wissen, ggf. auch jemand anderes.

**Comment by goaround** [comment]
Bin alle Möglichkeiten durchgegangen und konnte keinen Fehler mehr finden. Freue mich sehr auf das Update (wenn du schon dabei bist gerne auch einen neuen Release von Multisite Global Media mit meinem Fix für die REST API) :)

**Comment by bueltge** [comment]
Version 1.0.0 ist da und auch auf wp.org hinterlegt.

@goaround MGM - deinen PR habe ich bereits gemergt, nun wäre ein Tag und zip gut, das meinst du? Da es ja nicht auf wp.org abgelegt ist.

**Comment by goaround** [comment]
@bueltge genau, ich lade MGM über Composer, würde mich über 0.1.1 freuen :)

**Comment by bueltge** [comment]
@goaround nun nachgeholt, MGM hat einen neuen Tag.
