### ISSUE TITLE
[Bug]: PHP8.3 Deprecated: Function utf8_decode()

### ISSUE THREAD

**Issue by sterbekuenstler** [bueltge/de-DE#18]
### Description of the bug

Last plugin customization was a long time ago and if you switch to PHP8.3, you get an error message.

The upload and the naming seems to work, I uploaded length.jpg and it was renamed to length.jpg.

In some cases, the WordPress backend did not load when PHP8.3 and the current plugin version were running.

### Reproduction instructions

Update to PHP8.3

### Expected behavior

Nothing special expected

### Environment info

WordPress-Version: 6.4.2
PHP-Version: 8.3.1
MySQL/MariaDB-Version: 5.7.42

Aktive Plugins:
Borlabs Cookie (3.0.0.13)
Broken Link Checker (2.2.4)
Honeypot for Contact Form 7 (2.1.1)
Contact Form 7 (5.8.6)
Credit Tracker (1.1.17)
Exclude Image Thumbnails From UpdraftPlus Backups (1.0.3)
Download Monitor (4.9.5)
Mehrere Dateien per Drag & Drop hochladen - Kontaktformular 7 (1.3.7.5)
Yoast Duplicate Post (4.5)
Envira Gallery (1.9.9.2)
FileBird Pro (6.0.4)
Avada Builder (3.11.3)
Avada Core (5.11.3)
Indeed My Team (3.0)
InfiniteWP - Client (1.12.5)
NinjaFirewall (WP Edition) (4.5.10)
NinjaScanner (3.1)
Redirector (3.0.1)
Slider Revolution (6.6.20)
UpdraftPlus – Sichern/Wiederherstellen (2.23.14.26)
Yoast SEO (21.8)
WP Mail Logging (1.12.0)
WP Mail SMTP (3.11.0)

Aktives Theme: Avada Child (Avada 7.11.3)

### Relevant log output

```shell
Deprecated: Function utf8_decode() is deprecated in .../plugins/de_de/de_DE.php on line 332
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bueltge** [comment]
Should be fixed with commit https://github.com/bueltge/de-DE/commit/742ecafc01b18ac6765a4323f213489c85504e87 and released with version 1.0.1.
